modLoader="javafml"
loaderVersion="${loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/trade-cycling/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/trade-cycling"
logoFile="icon.png"
authors="${mod_vendor}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/trade_cycling.json"
description='''The trade cycling functionality from Easy Villagers.'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"